### ISSUE TITLE
First Release Checklist

### ISSUE THREAD

**Issue by apirogov** [Materials-Data-Science-and-Informatics/metador-core#42]
* [x] PyPI metadata in pyproject.toml
* [x] codemeta metadata
* [x] citation.cff metadata
* [x] check readme, tutorials and code docs state
* [x] see #2 
* [x] make sure tests succeed for all supported python versions
* [x] create release tag
* [x] push release to PyPI

Check out [portray](https://timothycrosley.github.io/portray/), which combines pdocs and mkdocs for code + high level documentation.

We should re-use the Jupyter tutorials and embed them somehow together with the auto-gen API docs.
